project_name: verify

release:
  prerelease: auto
  github:
    owner: pomerium
    name: sdk-go
  name_template: "v{{.Version}}"

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download
    - make build-deps

builds:
  - id: verify
    hooks:
      pre:
        - make build-deps
    main: ./_example/main.go
    binary: verify
    goarch:
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarm:
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm

    ldflags:
      - -s -w

snapshot:
  name_template: "{{ .Version }}+next+{{ .ShortCommit }}"

dockers:
  - image_templates:
      - "pomerium/verify:latest"
      - "pomerium/verify:{{ .Tag }}"
    dockerfile: .github/Dockerfile-release
    binaries:
      - verify
    build_flag_templates:
      - "--pull"
      - "--build-arg=ARCH=amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=repository=http://github.com/pomerium/sdk-go"
      - "--label=homepage=http://www.pomerium.io"
