version: "2"
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      - linters:
          - errcheck
        path: _test\.go$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/pomerium)
      custom-order: true
