// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: config.proto

package pomerium

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConfigServiceName is the fully-qualified name of the ConfigService service.
	ConfigServiceName = "pomerium.config.ConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConfigServiceCreateKeyPairProcedure is the fully-qualified name of the ConfigService's
	// CreateKeyPair RPC.
	ConfigServiceCreateKeyPairProcedure = "/pomerium.config.ConfigService/CreateKeyPair"
	// ConfigServiceCreatePolicyProcedure is the fully-qualified name of the ConfigService's
	// CreatePolicy RPC.
	ConfigServiceCreatePolicyProcedure = "/pomerium.config.ConfigService/CreatePolicy"
	// ConfigServiceCreateRouteProcedure is the fully-qualified name of the ConfigService's CreateRoute
	// RPC.
	ConfigServiceCreateRouteProcedure = "/pomerium.config.ConfigService/CreateRoute"
	// ConfigServiceCreateServiceAccountProcedure is the fully-qualified name of the ConfigService's
	// CreateServiceAccount RPC.
	ConfigServiceCreateServiceAccountProcedure = "/pomerium.config.ConfigService/CreateServiceAccount"
	// ConfigServiceDeleteKeyPairProcedure is the fully-qualified name of the ConfigService's
	// DeleteKeyPair RPC.
	ConfigServiceDeleteKeyPairProcedure = "/pomerium.config.ConfigService/DeleteKeyPair"
	// ConfigServiceDeletePolicyProcedure is the fully-qualified name of the ConfigService's
	// DeletePolicy RPC.
	ConfigServiceDeletePolicyProcedure = "/pomerium.config.ConfigService/DeletePolicy"
	// ConfigServiceDeleteRouteProcedure is the fully-qualified name of the ConfigService's DeleteRoute
	// RPC.
	ConfigServiceDeleteRouteProcedure = "/pomerium.config.ConfigService/DeleteRoute"
	// ConfigServiceDeleteServiceAccountProcedure is the fully-qualified name of the ConfigService's
	// DeleteServiceAccount RPC.
	ConfigServiceDeleteServiceAccountProcedure = "/pomerium.config.ConfigService/DeleteServiceAccount"
	// ConfigServiceGetKeyPairProcedure is the fully-qualified name of the ConfigService's GetKeyPair
	// RPC.
	ConfigServiceGetKeyPairProcedure = "/pomerium.config.ConfigService/GetKeyPair"
	// ConfigServiceGetPolicyProcedure is the fully-qualified name of the ConfigService's GetPolicy RPC.
	ConfigServiceGetPolicyProcedure = "/pomerium.config.ConfigService/GetPolicy"
	// ConfigServiceGetRouteProcedure is the fully-qualified name of the ConfigService's GetRoute RPC.
	ConfigServiceGetRouteProcedure = "/pomerium.config.ConfigService/GetRoute"
	// ConfigServiceGetServerInfoProcedure is the fully-qualified name of the ConfigService's
	// GetServerInfo RPC.
	ConfigServiceGetServerInfoProcedure = "/pomerium.config.ConfigService/GetServerInfo"
	// ConfigServiceGetServiceAccountProcedure is the fully-qualified name of the ConfigService's
	// GetServiceAccount RPC.
	ConfigServiceGetServiceAccountProcedure = "/pomerium.config.ConfigService/GetServiceAccount"
	// ConfigServiceGetSettingsProcedure is the fully-qualified name of the ConfigService's GetSettings
	// RPC.
	ConfigServiceGetSettingsProcedure = "/pomerium.config.ConfigService/GetSettings"
	// ConfigServiceListKeyPairsProcedure is the fully-qualified name of the ConfigService's
	// ListKeyPairs RPC.
	ConfigServiceListKeyPairsProcedure = "/pomerium.config.ConfigService/ListKeyPairs"
	// ConfigServiceListPoliciesProcedure is the fully-qualified name of the ConfigService's
	// ListPolicies RPC.
	ConfigServiceListPoliciesProcedure = "/pomerium.config.ConfigService/ListPolicies"
	// ConfigServiceListRoutesProcedure is the fully-qualified name of the ConfigService's ListRoutes
	// RPC.
	ConfigServiceListRoutesProcedure = "/pomerium.config.ConfigService/ListRoutes"
	// ConfigServiceListServiceAccountsProcedure is the fully-qualified name of the ConfigService's
	// ListServiceAccounts RPC.
	ConfigServiceListServiceAccountsProcedure = "/pomerium.config.ConfigService/ListServiceAccounts"
	// ConfigServiceListSettingsProcedure is the fully-qualified name of the ConfigService's
	// ListSettings RPC.
	ConfigServiceListSettingsProcedure = "/pomerium.config.ConfigService/ListSettings"
	// ConfigServiceUpdateKeyPairProcedure is the fully-qualified name of the ConfigService's
	// UpdateKeyPair RPC.
	ConfigServiceUpdateKeyPairProcedure = "/pomerium.config.ConfigService/UpdateKeyPair"
	// ConfigServiceUpdatePolicyProcedure is the fully-qualified name of the ConfigService's
	// UpdatePolicy RPC.
	ConfigServiceUpdatePolicyProcedure = "/pomerium.config.ConfigService/UpdatePolicy"
	// ConfigServiceUpdateRouteProcedure is the fully-qualified name of the ConfigService's UpdateRoute
	// RPC.
	ConfigServiceUpdateRouteProcedure = "/pomerium.config.ConfigService/UpdateRoute"
	// ConfigServiceUpdateServiceAccountProcedure is the fully-qualified name of the ConfigService's
	// UpdateServiceAccount RPC.
	ConfigServiceUpdateServiceAccountProcedure = "/pomerium.config.ConfigService/UpdateServiceAccount"
	// ConfigServiceUpdateSettingsProcedure is the fully-qualified name of the ConfigService's
	// UpdateSettings RPC.
	ConfigServiceUpdateSettingsProcedure = "/pomerium.config.ConfigService/UpdateSettings"
)

// ConfigServiceClient is a client for the pomerium.config.ConfigService service.
type ConfigServiceClient interface {
	CreateKeyPair(context.Context, *connect.Request[CreateKeyPairRequest]) (*connect.Response[CreateKeyPairResponse], error)
	CreatePolicy(context.Context, *connect.Request[CreatePolicyRequest]) (*connect.Response[CreatePolicyResponse], error)
	CreateRoute(context.Context, *connect.Request[CreateRouteRequest]) (*connect.Response[CreateRouteResponse], error)
	CreateServiceAccount(context.Context, *connect.Request[CreateServiceAccountRequest]) (*connect.Response[CreateServiceAccountResponse], error)
	DeleteKeyPair(context.Context, *connect.Request[DeleteKeyPairRequest]) (*connect.Response[DeleteKeyPairResponse], error)
	DeletePolicy(context.Context, *connect.Request[DeletePolicyRequest]) (*connect.Response[DeletePolicyResponse], error)
	DeleteRoute(context.Context, *connect.Request[DeleteRouteRequest]) (*connect.Response[DeleteRouteResponse], error)
	DeleteServiceAccount(context.Context, *connect.Request[DeleteServiceAccountRequest]) (*connect.Response[DeleteServiceAccountResponse], error)
	GetKeyPair(context.Context, *connect.Request[GetKeyPairRequest]) (*connect.Response[GetKeyPairResponse], error)
	GetPolicy(context.Context, *connect.Request[GetPolicyRequest]) (*connect.Response[GetPolicyResponse], error)
	GetRoute(context.Context, *connect.Request[GetRouteRequest]) (*connect.Response[GetRouteResponse], error)
	GetServerInfo(context.Context, *connect.Request[GetServerInfoRequest]) (*connect.Response[GetServerInfoResponse], error)
	GetServiceAccount(context.Context, *connect.Request[GetServiceAccountRequest]) (*connect.Response[GetServiceAccountResponse], error)
	GetSettings(context.Context, *connect.Request[GetSettingsRequest]) (*connect.Response[GetSettingsResponse], error)
	ListKeyPairs(context.Context, *connect.Request[ListKeyPairsRequest]) (*connect.Response[ListKeyPairsResponse], error)
	ListPolicies(context.Context, *connect.Request[ListPoliciesRequest]) (*connect.Response[ListPoliciesResponse], error)
	ListRoutes(context.Context, *connect.Request[ListRoutesRequest]) (*connect.Response[ListRoutesResponse], error)
	ListServiceAccounts(context.Context, *connect.Request[ListServiceAccountsRequest]) (*connect.Response[ListServiceAccountsResponse], error)
	ListSettings(context.Context, *connect.Request[ListSettingsRequest]) (*connect.Response[ListSettingsResponse], error)
	UpdateKeyPair(context.Context, *connect.Request[UpdateKeyPairRequest]) (*connect.Response[UpdateKeyPairResponse], error)
	UpdatePolicy(context.Context, *connect.Request[UpdatePolicyRequest]) (*connect.Response[UpdatePolicyResponse], error)
	UpdateRoute(context.Context, *connect.Request[UpdateRouteRequest]) (*connect.Response[UpdateRouteResponse], error)
	UpdateServiceAccount(context.Context, *connect.Request[UpdateServiceAccountRequest]) (*connect.Response[UpdateServiceAccountResponse], error)
	UpdateSettings(context.Context, *connect.Request[UpdateSettingsRequest]) (*connect.Response[UpdateSettingsResponse], error)
}

// NewConfigServiceClient constructs a client for the pomerium.config.ConfigService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	configServiceMethods := File_config_proto.Services().ByName("ConfigService").Methods()
	return &configServiceClient{
		createKeyPair: connect.NewClient[CreateKeyPairRequest, CreateKeyPairResponse](
			httpClient,
			baseURL+ConfigServiceCreateKeyPairProcedure,
			connect.WithSchema(configServiceMethods.ByName("CreateKeyPair")),
			connect.WithClientOptions(opts...),
		),
		createPolicy: connect.NewClient[CreatePolicyRequest, CreatePolicyResponse](
			httpClient,
			baseURL+ConfigServiceCreatePolicyProcedure,
			connect.WithSchema(configServiceMethods.ByName("CreatePolicy")),
			connect.WithClientOptions(opts...),
		),
		createRoute: connect.NewClient[CreateRouteRequest, CreateRouteResponse](
			httpClient,
			baseURL+ConfigServiceCreateRouteProcedure,
			connect.WithSchema(configServiceMethods.ByName("CreateRoute")),
			connect.WithClientOptions(opts...),
		),
		createServiceAccount: connect.NewClient[CreateServiceAccountRequest, CreateServiceAccountResponse](
			httpClient,
			baseURL+ConfigServiceCreateServiceAccountProcedure,
			connect.WithSchema(configServiceMethods.ByName("CreateServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		deleteKeyPair: connect.NewClient[DeleteKeyPairRequest, DeleteKeyPairResponse](
			httpClient,
			baseURL+ConfigServiceDeleteKeyPairProcedure,
			connect.WithSchema(configServiceMethods.ByName("DeleteKeyPair")),
			connect.WithClientOptions(opts...),
		),
		deletePolicy: connect.NewClient[DeletePolicyRequest, DeletePolicyResponse](
			httpClient,
			baseURL+ConfigServiceDeletePolicyProcedure,
			connect.WithSchema(configServiceMethods.ByName("DeletePolicy")),
			connect.WithClientOptions(opts...),
		),
		deleteRoute: connect.NewClient[DeleteRouteRequest, DeleteRouteResponse](
			httpClient,
			baseURL+ConfigServiceDeleteRouteProcedure,
			connect.WithSchema(configServiceMethods.ByName("DeleteRoute")),
			connect.WithClientOptions(opts...),
		),
		deleteServiceAccount: connect.NewClient[DeleteServiceAccountRequest, DeleteServiceAccountResponse](
			httpClient,
			baseURL+ConfigServiceDeleteServiceAccountProcedure,
			connect.WithSchema(configServiceMethods.ByName("DeleteServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		getKeyPair: connect.NewClient[GetKeyPairRequest, GetKeyPairResponse](
			httpClient,
			baseURL+ConfigServiceGetKeyPairProcedure,
			connect.WithSchema(configServiceMethods.ByName("GetKeyPair")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getPolicy: connect.NewClient[GetPolicyRequest, GetPolicyResponse](
			httpClient,
			baseURL+ConfigServiceGetPolicyProcedure,
			connect.WithSchema(configServiceMethods.ByName("GetPolicy")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getRoute: connect.NewClient[GetRouteRequest, GetRouteResponse](
			httpClient,
			baseURL+ConfigServiceGetRouteProcedure,
			connect.WithSchema(configServiceMethods.ByName("GetRoute")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getServerInfo: connect.NewClient[GetServerInfoRequest, GetServerInfoResponse](
			httpClient,
			baseURL+ConfigServiceGetServerInfoProcedure,
			connect.WithSchema(configServiceMethods.ByName("GetServerInfo")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getServiceAccount: connect.NewClient[GetServiceAccountRequest, GetServiceAccountResponse](
			httpClient,
			baseURL+ConfigServiceGetServiceAccountProcedure,
			connect.WithSchema(configServiceMethods.ByName("GetServiceAccount")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getSettings: connect.NewClient[GetSettingsRequest, GetSettingsResponse](
			httpClient,
			baseURL+ConfigServiceGetSettingsProcedure,
			connect.WithSchema(configServiceMethods.ByName("GetSettings")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listKeyPairs: connect.NewClient[ListKeyPairsRequest, ListKeyPairsResponse](
			httpClient,
			baseURL+ConfigServiceListKeyPairsProcedure,
			connect.WithSchema(configServiceMethods.ByName("ListKeyPairs")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listPolicies: connect.NewClient[ListPoliciesRequest, ListPoliciesResponse](
			httpClient,
			baseURL+ConfigServiceListPoliciesProcedure,
			connect.WithSchema(configServiceMethods.ByName("ListPolicies")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listRoutes: connect.NewClient[ListRoutesRequest, ListRoutesResponse](
			httpClient,
			baseURL+ConfigServiceListRoutesProcedure,
			connect.WithSchema(configServiceMethods.ByName("ListRoutes")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listServiceAccounts: connect.NewClient[ListServiceAccountsRequest, ListServiceAccountsResponse](
			httpClient,
			baseURL+ConfigServiceListServiceAccountsProcedure,
			connect.WithSchema(configServiceMethods.ByName("ListServiceAccounts")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listSettings: connect.NewClient[ListSettingsRequest, ListSettingsResponse](
			httpClient,
			baseURL+ConfigServiceListSettingsProcedure,
			connect.WithSchema(configServiceMethods.ByName("ListSettings")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateKeyPair: connect.NewClient[UpdateKeyPairRequest, UpdateKeyPairResponse](
			httpClient,
			baseURL+ConfigServiceUpdateKeyPairProcedure,
			connect.WithSchema(configServiceMethods.ByName("UpdateKeyPair")),
			connect.WithClientOptions(opts...),
		),
		updatePolicy: connect.NewClient[UpdatePolicyRequest, UpdatePolicyResponse](
			httpClient,
			baseURL+ConfigServiceUpdatePolicyProcedure,
			connect.WithSchema(configServiceMethods.ByName("UpdatePolicy")),
			connect.WithClientOptions(opts...),
		),
		updateRoute: connect.NewClient[UpdateRouteRequest, UpdateRouteResponse](
			httpClient,
			baseURL+ConfigServiceUpdateRouteProcedure,
			connect.WithSchema(configServiceMethods.ByName("UpdateRoute")),
			connect.WithClientOptions(opts...),
		),
		updateServiceAccount: connect.NewClient[UpdateServiceAccountRequest, UpdateServiceAccountResponse](
			httpClient,
			baseURL+ConfigServiceUpdateServiceAccountProcedure,
			connect.WithSchema(configServiceMethods.ByName("UpdateServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		updateSettings: connect.NewClient[UpdateSettingsRequest, UpdateSettingsResponse](
			httpClient,
			baseURL+ConfigServiceUpdateSettingsProcedure,
			connect.WithSchema(configServiceMethods.ByName("UpdateSettings")),
			connect.WithClientOptions(opts...),
		),
	}
}

// configServiceClient implements ConfigServiceClient.
type configServiceClient struct {
	createKeyPair        *connect.Client[CreateKeyPairRequest, CreateKeyPairResponse]
	createPolicy         *connect.Client[CreatePolicyRequest, CreatePolicyResponse]
	createRoute          *connect.Client[CreateRouteRequest, CreateRouteResponse]
	createServiceAccount *connect.Client[CreateServiceAccountRequest, CreateServiceAccountResponse]
	deleteKeyPair        *connect.Client[DeleteKeyPairRequest, DeleteKeyPairResponse]
	deletePolicy         *connect.Client[DeletePolicyRequest, DeletePolicyResponse]
	deleteRoute          *connect.Client[DeleteRouteRequest, DeleteRouteResponse]
	deleteServiceAccount *connect.Client[DeleteServiceAccountRequest, DeleteServiceAccountResponse]
	getKeyPair           *connect.Client[GetKeyPairRequest, GetKeyPairResponse]
	getPolicy            *connect.Client[GetPolicyRequest, GetPolicyResponse]
	getRoute             *connect.Client[GetRouteRequest, GetRouteResponse]
	getServerInfo        *connect.Client[GetServerInfoRequest, GetServerInfoResponse]
	getServiceAccount    *connect.Client[GetServiceAccountRequest, GetServiceAccountResponse]
	getSettings          *connect.Client[GetSettingsRequest, GetSettingsResponse]
	listKeyPairs         *connect.Client[ListKeyPairsRequest, ListKeyPairsResponse]
	listPolicies         *connect.Client[ListPoliciesRequest, ListPoliciesResponse]
	listRoutes           *connect.Client[ListRoutesRequest, ListRoutesResponse]
	listServiceAccounts  *connect.Client[ListServiceAccountsRequest, ListServiceAccountsResponse]
	listSettings         *connect.Client[ListSettingsRequest, ListSettingsResponse]
	updateKeyPair        *connect.Client[UpdateKeyPairRequest, UpdateKeyPairResponse]
	updatePolicy         *connect.Client[UpdatePolicyRequest, UpdatePolicyResponse]
	updateRoute          *connect.Client[UpdateRouteRequest, UpdateRouteResponse]
	updateServiceAccount *connect.Client[UpdateServiceAccountRequest, UpdateServiceAccountResponse]
	updateSettings       *connect.Client[UpdateSettingsRequest, UpdateSettingsResponse]
}

// CreateKeyPair calls pomerium.config.ConfigService.CreateKeyPair.
func (c *configServiceClient) CreateKeyPair(ctx context.Context, req *connect.Request[CreateKeyPairRequest]) (*connect.Response[CreateKeyPairResponse], error) {
	return c.createKeyPair.CallUnary(ctx, req)
}

// CreatePolicy calls pomerium.config.ConfigService.CreatePolicy.
func (c *configServiceClient) CreatePolicy(ctx context.Context, req *connect.Request[CreatePolicyRequest]) (*connect.Response[CreatePolicyResponse], error) {
	return c.createPolicy.CallUnary(ctx, req)
}

// CreateRoute calls pomerium.config.ConfigService.CreateRoute.
func (c *configServiceClient) CreateRoute(ctx context.Context, req *connect.Request[CreateRouteRequest]) (*connect.Response[CreateRouteResponse], error) {
	return c.createRoute.CallUnary(ctx, req)
}

// CreateServiceAccount calls pomerium.config.ConfigService.CreateServiceAccount.
func (c *configServiceClient) CreateServiceAccount(ctx context.Context, req *connect.Request[CreateServiceAccountRequest]) (*connect.Response[CreateServiceAccountResponse], error) {
	return c.createServiceAccount.CallUnary(ctx, req)
}

// DeleteKeyPair calls pomerium.config.ConfigService.DeleteKeyPair.
func (c *configServiceClient) DeleteKeyPair(ctx context.Context, req *connect.Request[DeleteKeyPairRequest]) (*connect.Response[DeleteKeyPairResponse], error) {
	return c.deleteKeyPair.CallUnary(ctx, req)
}

// DeletePolicy calls pomerium.config.ConfigService.DeletePolicy.
func (c *configServiceClient) DeletePolicy(ctx context.Context, req *connect.Request[DeletePolicyRequest]) (*connect.Response[DeletePolicyResponse], error) {
	return c.deletePolicy.CallUnary(ctx, req)
}

// DeleteRoute calls pomerium.config.ConfigService.DeleteRoute.
func (c *configServiceClient) DeleteRoute(ctx context.Context, req *connect.Request[DeleteRouteRequest]) (*connect.Response[DeleteRouteResponse], error) {
	return c.deleteRoute.CallUnary(ctx, req)
}

// DeleteServiceAccount calls pomerium.config.ConfigService.DeleteServiceAccount.
func (c *configServiceClient) DeleteServiceAccount(ctx context.Context, req *connect.Request[DeleteServiceAccountRequest]) (*connect.Response[DeleteServiceAccountResponse], error) {
	return c.deleteServiceAccount.CallUnary(ctx, req)
}

// GetKeyPair calls pomerium.config.ConfigService.GetKeyPair.
func (c *configServiceClient) GetKeyPair(ctx context.Context, req *connect.Request[GetKeyPairRequest]) (*connect.Response[GetKeyPairResponse], error) {
	return c.getKeyPair.CallUnary(ctx, req)
}

// GetPolicy calls pomerium.config.ConfigService.GetPolicy.
func (c *configServiceClient) GetPolicy(ctx context.Context, req *connect.Request[GetPolicyRequest]) (*connect.Response[GetPolicyResponse], error) {
	return c.getPolicy.CallUnary(ctx, req)
}

// GetRoute calls pomerium.config.ConfigService.GetRoute.
func (c *configServiceClient) GetRoute(ctx context.Context, req *connect.Request[GetRouteRequest]) (*connect.Response[GetRouteResponse], error) {
	return c.getRoute.CallUnary(ctx, req)
}

// GetServerInfo calls pomerium.config.ConfigService.GetServerInfo.
func (c *configServiceClient) GetServerInfo(ctx context.Context, req *connect.Request[GetServerInfoRequest]) (*connect.Response[GetServerInfoResponse], error) {
	return c.getServerInfo.CallUnary(ctx, req)
}

// GetServiceAccount calls pomerium.config.ConfigService.GetServiceAccount.
func (c *configServiceClient) GetServiceAccount(ctx context.Context, req *connect.Request[GetServiceAccountRequest]) (*connect.Response[GetServiceAccountResponse], error) {
	return c.getServiceAccount.CallUnary(ctx, req)
}

// GetSettings calls pomerium.config.ConfigService.GetSettings.
func (c *configServiceClient) GetSettings(ctx context.Context, req *connect.Request[GetSettingsRequest]) (*connect.Response[GetSettingsResponse], error) {
	return c.getSettings.CallUnary(ctx, req)
}

// ListKeyPairs calls pomerium.config.ConfigService.ListKeyPairs.
func (c *configServiceClient) ListKeyPairs(ctx context.Context, req *connect.Request[ListKeyPairsRequest]) (*connect.Response[ListKeyPairsResponse], error) {
	return c.listKeyPairs.CallUnary(ctx, req)
}

// ListPolicies calls pomerium.config.ConfigService.ListPolicies.
func (c *configServiceClient) ListPolicies(ctx context.Context, req *connect.Request[ListPoliciesRequest]) (*connect.Response[ListPoliciesResponse], error) {
	return c.listPolicies.CallUnary(ctx, req)
}

// ListRoutes calls pomerium.config.ConfigService.ListRoutes.
func (c *configServiceClient) ListRoutes(ctx context.Context, req *connect.Request[ListRoutesRequest]) (*connect.Response[ListRoutesResponse], error) {
	return c.listRoutes.CallUnary(ctx, req)
}

// ListServiceAccounts calls pomerium.config.ConfigService.ListServiceAccounts.
func (c *configServiceClient) ListServiceAccounts(ctx context.Context, req *connect.Request[ListServiceAccountsRequest]) (*connect.Response[ListServiceAccountsResponse], error) {
	return c.listServiceAccounts.CallUnary(ctx, req)
}

// ListSettings calls pomerium.config.ConfigService.ListSettings.
func (c *configServiceClient) ListSettings(ctx context.Context, req *connect.Request[ListSettingsRequest]) (*connect.Response[ListSettingsResponse], error) {
	return c.listSettings.CallUnary(ctx, req)
}

// UpdateKeyPair calls pomerium.config.ConfigService.UpdateKeyPair.
func (c *configServiceClient) UpdateKeyPair(ctx context.Context, req *connect.Request[UpdateKeyPairRequest]) (*connect.Response[UpdateKeyPairResponse], error) {
	return c.updateKeyPair.CallUnary(ctx, req)
}

// UpdatePolicy calls pomerium.config.ConfigService.UpdatePolicy.
func (c *configServiceClient) UpdatePolicy(ctx context.Context, req *connect.Request[UpdatePolicyRequest]) (*connect.Response[UpdatePolicyResponse], error) {
	return c.updatePolicy.CallUnary(ctx, req)
}

// UpdateRoute calls pomerium.config.ConfigService.UpdateRoute.
func (c *configServiceClient) UpdateRoute(ctx context.Context, req *connect.Request[UpdateRouteRequest]) (*connect.Response[UpdateRouteResponse], error) {
	return c.updateRoute.CallUnary(ctx, req)
}

// UpdateServiceAccount calls pomerium.config.ConfigService.UpdateServiceAccount.
func (c *configServiceClient) UpdateServiceAccount(ctx context.Context, req *connect.Request[UpdateServiceAccountRequest]) (*connect.Response[UpdateServiceAccountResponse], error) {
	return c.updateServiceAccount.CallUnary(ctx, req)
}

// UpdateSettings calls pomerium.config.ConfigService.UpdateSettings.
func (c *configServiceClient) UpdateSettings(ctx context.Context, req *connect.Request[UpdateSettingsRequest]) (*connect.Response[UpdateSettingsResponse], error) {
	return c.updateSettings.CallUnary(ctx, req)
}

// ConfigServiceHandler is an implementation of the pomerium.config.ConfigService service.
type ConfigServiceHandler interface {
	CreateKeyPair(context.Context, *connect.Request[CreateKeyPairRequest]) (*connect.Response[CreateKeyPairResponse], error)
	CreatePolicy(context.Context, *connect.Request[CreatePolicyRequest]) (*connect.Response[CreatePolicyResponse], error)
	CreateRoute(context.Context, *connect.Request[CreateRouteRequest]) (*connect.Response[CreateRouteResponse], error)
	CreateServiceAccount(context.Context, *connect.Request[CreateServiceAccountRequest]) (*connect.Response[CreateServiceAccountResponse], error)
	DeleteKeyPair(context.Context, *connect.Request[DeleteKeyPairRequest]) (*connect.Response[DeleteKeyPairResponse], error)
	DeletePolicy(context.Context, *connect.Request[DeletePolicyRequest]) (*connect.Response[DeletePolicyResponse], error)
	DeleteRoute(context.Context, *connect.Request[DeleteRouteRequest]) (*connect.Response[DeleteRouteResponse], error)
	DeleteServiceAccount(context.Context, *connect.Request[DeleteServiceAccountRequest]) (*connect.Response[DeleteServiceAccountResponse], error)
	GetKeyPair(context.Context, *connect.Request[GetKeyPairRequest]) (*connect.Response[GetKeyPairResponse], error)
	GetPolicy(context.Context, *connect.Request[GetPolicyRequest]) (*connect.Response[GetPolicyResponse], error)
	GetRoute(context.Context, *connect.Request[GetRouteRequest]) (*connect.Response[GetRouteResponse], error)
	GetServerInfo(context.Context, *connect.Request[GetServerInfoRequest]) (*connect.Response[GetServerInfoResponse], error)
	GetServiceAccount(context.Context, *connect.Request[GetServiceAccountRequest]) (*connect.Response[GetServiceAccountResponse], error)
	GetSettings(context.Context, *connect.Request[GetSettingsRequest]) (*connect.Response[GetSettingsResponse], error)
	ListKeyPairs(context.Context, *connect.Request[ListKeyPairsRequest]) (*connect.Response[ListKeyPairsResponse], error)
	ListPolicies(context.Context, *connect.Request[ListPoliciesRequest]) (*connect.Response[ListPoliciesResponse], error)
	ListRoutes(context.Context, *connect.Request[ListRoutesRequest]) (*connect.Response[ListRoutesResponse], error)
	ListServiceAccounts(context.Context, *connect.Request[ListServiceAccountsRequest]) (*connect.Response[ListServiceAccountsResponse], error)
	ListSettings(context.Context, *connect.Request[ListSettingsRequest]) (*connect.Response[ListSettingsResponse], error)
	UpdateKeyPair(context.Context, *connect.Request[UpdateKeyPairRequest]) (*connect.Response[UpdateKeyPairResponse], error)
	UpdatePolicy(context.Context, *connect.Request[UpdatePolicyRequest]) (*connect.Response[UpdatePolicyResponse], error)
	UpdateRoute(context.Context, *connect.Request[UpdateRouteRequest]) (*connect.Response[UpdateRouteResponse], error)
	UpdateServiceAccount(context.Context, *connect.Request[UpdateServiceAccountRequest]) (*connect.Response[UpdateServiceAccountResponse], error)
	UpdateSettings(context.Context, *connect.Request[UpdateSettingsRequest]) (*connect.Response[UpdateSettingsResponse], error)
}

// NewConfigServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfigServiceHandler(svc ConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	configServiceMethods := File_config_proto.Services().ByName("ConfigService").Methods()
	configServiceCreateKeyPairHandler := connect.NewUnaryHandler(
		ConfigServiceCreateKeyPairProcedure,
		svc.CreateKeyPair,
		connect.WithSchema(configServiceMethods.ByName("CreateKeyPair")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceCreatePolicyHandler := connect.NewUnaryHandler(
		ConfigServiceCreatePolicyProcedure,
		svc.CreatePolicy,
		connect.WithSchema(configServiceMethods.ByName("CreatePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceCreateRouteHandler := connect.NewUnaryHandler(
		ConfigServiceCreateRouteProcedure,
		svc.CreateRoute,
		connect.WithSchema(configServiceMethods.ByName("CreateRoute")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceCreateServiceAccountHandler := connect.NewUnaryHandler(
		ConfigServiceCreateServiceAccountProcedure,
		svc.CreateServiceAccount,
		connect.WithSchema(configServiceMethods.ByName("CreateServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceDeleteKeyPairHandler := connect.NewUnaryHandler(
		ConfigServiceDeleteKeyPairProcedure,
		svc.DeleteKeyPair,
		connect.WithSchema(configServiceMethods.ByName("DeleteKeyPair")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceDeletePolicyHandler := connect.NewUnaryHandler(
		ConfigServiceDeletePolicyProcedure,
		svc.DeletePolicy,
		connect.WithSchema(configServiceMethods.ByName("DeletePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceDeleteRouteHandler := connect.NewUnaryHandler(
		ConfigServiceDeleteRouteProcedure,
		svc.DeleteRoute,
		connect.WithSchema(configServiceMethods.ByName("DeleteRoute")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceDeleteServiceAccountHandler := connect.NewUnaryHandler(
		ConfigServiceDeleteServiceAccountProcedure,
		svc.DeleteServiceAccount,
		connect.WithSchema(configServiceMethods.ByName("DeleteServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceGetKeyPairHandler := connect.NewUnaryHandler(
		ConfigServiceGetKeyPairProcedure,
		svc.GetKeyPair,
		connect.WithSchema(configServiceMethods.ByName("GetKeyPair")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	configServiceGetPolicyHandler := connect.NewUnaryHandler(
		ConfigServiceGetPolicyProcedure,
		svc.GetPolicy,
		connect.WithSchema(configServiceMethods.ByName("GetPolicy")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	configServiceGetRouteHandler := connect.NewUnaryHandler(
		ConfigServiceGetRouteProcedure,
		svc.GetRoute,
		connect.WithSchema(configServiceMethods.ByName("GetRoute")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	configServiceGetServerInfoHandler := connect.NewUnaryHandler(
		ConfigServiceGetServerInfoProcedure,
		svc.GetServerInfo,
		connect.WithSchema(configServiceMethods.ByName("GetServerInfo")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	configServiceGetServiceAccountHandler := connect.NewUnaryHandler(
		ConfigServiceGetServiceAccountProcedure,
		svc.GetServiceAccount,
		connect.WithSchema(configServiceMethods.ByName("GetServiceAccount")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	configServiceGetSettingsHandler := connect.NewUnaryHandler(
		ConfigServiceGetSettingsProcedure,
		svc.GetSettings,
		connect.WithSchema(configServiceMethods.ByName("GetSettings")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	configServiceListKeyPairsHandler := connect.NewUnaryHandler(
		ConfigServiceListKeyPairsProcedure,
		svc.ListKeyPairs,
		connect.WithSchema(configServiceMethods.ByName("ListKeyPairs")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	configServiceListPoliciesHandler := connect.NewUnaryHandler(
		ConfigServiceListPoliciesProcedure,
		svc.ListPolicies,
		connect.WithSchema(configServiceMethods.ByName("ListPolicies")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	configServiceListRoutesHandler := connect.NewUnaryHandler(
		ConfigServiceListRoutesProcedure,
		svc.ListRoutes,
		connect.WithSchema(configServiceMethods.ByName("ListRoutes")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	configServiceListServiceAccountsHandler := connect.NewUnaryHandler(
		ConfigServiceListServiceAccountsProcedure,
		svc.ListServiceAccounts,
		connect.WithSchema(configServiceMethods.ByName("ListServiceAccounts")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	configServiceListSettingsHandler := connect.NewUnaryHandler(
		ConfigServiceListSettingsProcedure,
		svc.ListSettings,
		connect.WithSchema(configServiceMethods.ByName("ListSettings")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	configServiceUpdateKeyPairHandler := connect.NewUnaryHandler(
		ConfigServiceUpdateKeyPairProcedure,
		svc.UpdateKeyPair,
		connect.WithSchema(configServiceMethods.ByName("UpdateKeyPair")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceUpdatePolicyHandler := connect.NewUnaryHandler(
		ConfigServiceUpdatePolicyProcedure,
		svc.UpdatePolicy,
		connect.WithSchema(configServiceMethods.ByName("UpdatePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceUpdateRouteHandler := connect.NewUnaryHandler(
		ConfigServiceUpdateRouteProcedure,
		svc.UpdateRoute,
		connect.WithSchema(configServiceMethods.ByName("UpdateRoute")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceUpdateServiceAccountHandler := connect.NewUnaryHandler(
		ConfigServiceUpdateServiceAccountProcedure,
		svc.UpdateServiceAccount,
		connect.WithSchema(configServiceMethods.ByName("UpdateServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceUpdateSettingsHandler := connect.NewUnaryHandler(
		ConfigServiceUpdateSettingsProcedure,
		svc.UpdateSettings,
		connect.WithSchema(configServiceMethods.ByName("UpdateSettings")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pomerium.config.ConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfigServiceCreateKeyPairProcedure:
			configServiceCreateKeyPairHandler.ServeHTTP(w, r)
		case ConfigServiceCreatePolicyProcedure:
			configServiceCreatePolicyHandler.ServeHTTP(w, r)
		case ConfigServiceCreateRouteProcedure:
			configServiceCreateRouteHandler.ServeHTTP(w, r)
		case ConfigServiceCreateServiceAccountProcedure:
			configServiceCreateServiceAccountHandler.ServeHTTP(w, r)
		case ConfigServiceDeleteKeyPairProcedure:
			configServiceDeleteKeyPairHandler.ServeHTTP(w, r)
		case ConfigServiceDeletePolicyProcedure:
			configServiceDeletePolicyHandler.ServeHTTP(w, r)
		case ConfigServiceDeleteRouteProcedure:
			configServiceDeleteRouteHandler.ServeHTTP(w, r)
		case ConfigServiceDeleteServiceAccountProcedure:
			configServiceDeleteServiceAccountHandler.ServeHTTP(w, r)
		case ConfigServiceGetKeyPairProcedure:
			configServiceGetKeyPairHandler.ServeHTTP(w, r)
		case ConfigServiceGetPolicyProcedure:
			configServiceGetPolicyHandler.ServeHTTP(w, r)
		case ConfigServiceGetRouteProcedure:
			configServiceGetRouteHandler.ServeHTTP(w, r)
		case ConfigServiceGetServerInfoProcedure:
			configServiceGetServerInfoHandler.ServeHTTP(w, r)
		case ConfigServiceGetServiceAccountProcedure:
			configServiceGetServiceAccountHandler.ServeHTTP(w, r)
		case ConfigServiceGetSettingsProcedure:
			configServiceGetSettingsHandler.ServeHTTP(w, r)
		case ConfigServiceListKeyPairsProcedure:
			configServiceListKeyPairsHandler.ServeHTTP(w, r)
		case ConfigServiceListPoliciesProcedure:
			configServiceListPoliciesHandler.ServeHTTP(w, r)
		case ConfigServiceListRoutesProcedure:
			configServiceListRoutesHandler.ServeHTTP(w, r)
		case ConfigServiceListServiceAccountsProcedure:
			configServiceListServiceAccountsHandler.ServeHTTP(w, r)
		case ConfigServiceListSettingsProcedure:
			configServiceListSettingsHandler.ServeHTTP(w, r)
		case ConfigServiceUpdateKeyPairProcedure:
			configServiceUpdateKeyPairHandler.ServeHTTP(w, r)
		case ConfigServiceUpdatePolicyProcedure:
			configServiceUpdatePolicyHandler.ServeHTTP(w, r)
		case ConfigServiceUpdateRouteProcedure:
			configServiceUpdateRouteHandler.ServeHTTP(w, r)
		case ConfigServiceUpdateServiceAccountProcedure:
			configServiceUpdateServiceAccountHandler.ServeHTTP(w, r)
		case ConfigServiceUpdateSettingsProcedure:
			configServiceUpdateSettingsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfigServiceHandler struct{}

func (UnimplementedConfigServiceHandler) CreateKeyPair(context.Context, *connect.Request[CreateKeyPairRequest]) (*connect.Response[CreateKeyPairResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.CreateKeyPair is not implemented"))
}

func (UnimplementedConfigServiceHandler) CreatePolicy(context.Context, *connect.Request[CreatePolicyRequest]) (*connect.Response[CreatePolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.CreatePolicy is not implemented"))
}

func (UnimplementedConfigServiceHandler) CreateRoute(context.Context, *connect.Request[CreateRouteRequest]) (*connect.Response[CreateRouteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.CreateRoute is not implemented"))
}

func (UnimplementedConfigServiceHandler) CreateServiceAccount(context.Context, *connect.Request[CreateServiceAccountRequest]) (*connect.Response[CreateServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.CreateServiceAccount is not implemented"))
}

func (UnimplementedConfigServiceHandler) DeleteKeyPair(context.Context, *connect.Request[DeleteKeyPairRequest]) (*connect.Response[DeleteKeyPairResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.DeleteKeyPair is not implemented"))
}

func (UnimplementedConfigServiceHandler) DeletePolicy(context.Context, *connect.Request[DeletePolicyRequest]) (*connect.Response[DeletePolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.DeletePolicy is not implemented"))
}

func (UnimplementedConfigServiceHandler) DeleteRoute(context.Context, *connect.Request[DeleteRouteRequest]) (*connect.Response[DeleteRouteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.DeleteRoute is not implemented"))
}

func (UnimplementedConfigServiceHandler) DeleteServiceAccount(context.Context, *connect.Request[DeleteServiceAccountRequest]) (*connect.Response[DeleteServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.DeleteServiceAccount is not implemented"))
}

func (UnimplementedConfigServiceHandler) GetKeyPair(context.Context, *connect.Request[GetKeyPairRequest]) (*connect.Response[GetKeyPairResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.GetKeyPair is not implemented"))
}

func (UnimplementedConfigServiceHandler) GetPolicy(context.Context, *connect.Request[GetPolicyRequest]) (*connect.Response[GetPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.GetPolicy is not implemented"))
}

func (UnimplementedConfigServiceHandler) GetRoute(context.Context, *connect.Request[GetRouteRequest]) (*connect.Response[GetRouteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.GetRoute is not implemented"))
}

func (UnimplementedConfigServiceHandler) GetServerInfo(context.Context, *connect.Request[GetServerInfoRequest]) (*connect.Response[GetServerInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.GetServerInfo is not implemented"))
}

func (UnimplementedConfigServiceHandler) GetServiceAccount(context.Context, *connect.Request[GetServiceAccountRequest]) (*connect.Response[GetServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.GetServiceAccount is not implemented"))
}

func (UnimplementedConfigServiceHandler) GetSettings(context.Context, *connect.Request[GetSettingsRequest]) (*connect.Response[GetSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.GetSettings is not implemented"))
}

func (UnimplementedConfigServiceHandler) ListKeyPairs(context.Context, *connect.Request[ListKeyPairsRequest]) (*connect.Response[ListKeyPairsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.ListKeyPairs is not implemented"))
}

func (UnimplementedConfigServiceHandler) ListPolicies(context.Context, *connect.Request[ListPoliciesRequest]) (*connect.Response[ListPoliciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.ListPolicies is not implemented"))
}

func (UnimplementedConfigServiceHandler) ListRoutes(context.Context, *connect.Request[ListRoutesRequest]) (*connect.Response[ListRoutesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.ListRoutes is not implemented"))
}

func (UnimplementedConfigServiceHandler) ListServiceAccounts(context.Context, *connect.Request[ListServiceAccountsRequest]) (*connect.Response[ListServiceAccountsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.ListServiceAccounts is not implemented"))
}

func (UnimplementedConfigServiceHandler) ListSettings(context.Context, *connect.Request[ListSettingsRequest]) (*connect.Response[ListSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.ListSettings is not implemented"))
}

func (UnimplementedConfigServiceHandler) UpdateKeyPair(context.Context, *connect.Request[UpdateKeyPairRequest]) (*connect.Response[UpdateKeyPairResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.UpdateKeyPair is not implemented"))
}

func (UnimplementedConfigServiceHandler) UpdatePolicy(context.Context, *connect.Request[UpdatePolicyRequest]) (*connect.Response[UpdatePolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.UpdatePolicy is not implemented"))
}

func (UnimplementedConfigServiceHandler) UpdateRoute(context.Context, *connect.Request[UpdateRouteRequest]) (*connect.Response[UpdateRouteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.UpdateRoute is not implemented"))
}

func (UnimplementedConfigServiceHandler) UpdateServiceAccount(context.Context, *connect.Request[UpdateServiceAccountRequest]) (*connect.Response[UpdateServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.UpdateServiceAccount is not implemented"))
}

func (UnimplementedConfigServiceHandler) UpdateSettings(context.Context, *connect.Request[UpdateSettingsRequest]) (*connect.Response[UpdateSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pomerium.config.ConfigService.UpdateSettings is not implemented"))
}
