#!/bin/bash
set -euo pipefail

_scripts_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
_root_dir="$(dirname "$_scripts_dir")"
_deps_dir="$_root_dir/deps"

protoc \
	--plugin="protoc-gen-connect-go=$_scripts_dir/protoc-gen-connect-go" \
	--plugin="protoc-gen-go=$_scripts_dir/protoc-gen-go" \
	--proto_path="$(go list -m -f '{{.Dir}}' github.com/envoyproxy/protoc-gen-validate)" \
	--proto_path="$_deps_dir/github.com/pomerium/pomerium/pkg/grpc/config" \
	--go_out="." \
	--go_opt="Mconfig.proto=internal/config" \
	--connect-go_out="./internal" \
	--connect-go_opt="paths=source_relative" \
	--connect-go_opt="Mconfig.proto=github.com/pomerium/sdk-go/internal/config" \
	config.proto
